/* Do not edit, autogenerated by flexx.pyscript */

(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define([], factory);
    } else if (typeof exports !== 'undefined') {
        // Node or CommonJS
        module.exports = factory();
        if (typeof window === 'undefined') {
            root.mymodule = module.exports;  // also create global module in Node
        }
    } else {
        // Browser globals (root is window)
        root.mymodule = factory();
    }
}(this, function () {
    var py_hasattr = function (ob, name) {
        return (ob !== undefined) && (ob !== null) && (ob[name] !== undefined);
    };
    var Bar, Foo;
    // Example on how to create a JavaScript module using PyScript.
    // 
    // PyScript creates AMD modules that can be used in the browser, in nodejs,
    // and in combination with browserify and related tools.

    Foo = function () {
        if (this.__init__) {
           this.__init__.apply(this, arguments);
        }
    };
    Foo.prototype._base_class = Object;
    

    Foo.prototype.a_constant = [1, 2, 3];
    Foo.prototype.ham = function (x) {
        this.x = x;
        return null;
    };

    Foo.prototype.eggs = function (y) {
        this.y = this.x * y;
        py_hasattr(y, str);
        return null;
    };


    Bar = function () {
        if (this.__init__) {
           this.__init__.apply(this, arguments);
        }
    };
    Bar.prototype = Object.create(Foo.prototype);
    Bar.prototype._base_class = Foo.prototype;
    

    Bar.prototype.bla = function (z) {
        console.log(z);
        return null;
    };


    return {'Bar': Bar, 'Foo': Foo};
}));
