# Travis CI configuration file for Flexx
# Validate this at http://lint.travis-ci.org/

language: python

# use container-based infrastructure
sudo : false

matrix:
    include:
        - python: "3.3"
          env: TEST_UNIT=1
        - python: "3.4"
          env: TEST_UNIT=1 TEST_INSTALL=1
        - python: "3.5"
          env: TEST_UNIT=1
        - python: "pypy3"
          env: TEST_UNIT=1
        - python: "3.4"
          env: TEST_UNIT=0 TEST_DOCS=1
        - python: "3.4"
          env: TEST_UNIT=0 TEST_FLAKE=1

before_install:
    - REDIRECT_TO=/dev/stdout  # change to /dev/null to silence Travis

# Install dependencies
install:
    - if [ "${TEST_UNIT}" == "1" ]; then
        pip install pytest-cov;
        pip install tornado;
      fi;
    - if [ "${TEST_INSTALL}" == "1" ]; then
        python setup.py install;
        cd ~;
      fi;
    - if [ "${TEST_FLAKE}" == "1" ]; then
        pip install flake8;
      fi;
    - if [ "${TEST_DOCS}" == "1" ]; then
        pip install sphinx;
        pip install tornado;
      fi;

before_script:

# Run the tests
script: 
    - python -c "import sys; print(sys.version, '\n', sys.prefix)"
    
    - if [ "${TEST_UNIT}" == "1" ]; then
        python make test unit;
      fi;
    - if [ "${TEST_FLAKE}" == "1" ]; then
        #python make test style;
        echo Not doing flake tests for now ...
      fi;
    - if [ "${TEST_DOCS}" == "1" ]; then
        python make docs html;
      fi;

after_success:
    - echo SUCCESS!

after_failure:
    - echo FAIL!

after_script:
