# Travis CI configuration file for Zoof
# Resources:
# Validate this at http://lint.travis-ci.org/

language: python



python:
    # all versions except pypy and pypy3 have numpy as well.
    # -> TRAVIS_PYTHON_VERSION
    # Versions we want some lib code to work on
    - "pypy3"
    - "2.6"
    - "2.7"
    - "3.2"
    # For GUI stuff
    - "3.3"  # Will install miniconda /w PyQt4
    - "3.4"  # Will install miniconda /w PySide


before_install:
    - REDIRECT_TO=/dev/stdout  # change to /dev/null to silence Travis
    - if [ "${TRAVIS_PYTHON_VERSION}" == "3.3" ]; then
        wget -q http://repo.continuum.io/miniconda/Miniconda-3.6.0-Linux-x86_64.sh -O miniconda.sh;
        chmod +x miniconda.sh;
        ./miniconda.sh -b -p ~/anaconda &> ${REDIRECT_TO};
        export PATH=~/anaconda/bin:$PATH;
        conda update --yes --quiet conda &> ${REDIRECT_TO};
      fi;

# Install dependencies
install:
    - if [ "${TRAVIS_PYTHON_VERSION}" == "3.3" ]; then
        conda create -n testenv --yes --quiet pip python=$TRAVIS_PYTHON_VERSION > ${REDIRECT_TO};
        source activate testenv > ${REDIRECT_TO};
        conda install --yes --quiet pytest pyqt > ${REDIRECT_TO};
      fi;

before_script:


# Run the tests
script: 
    - python -c "import sys; print(sys.version, '\n', sys.prefix)"
    # - python make test X


after_success:
    - echo SUCCESS!

after_failure:
    - echo FAIL!

after_script:
